apiVersion: 1

datasources:
  - name: Cortex
    type: prometheus
    access: proxy
    orgId: 1
    url: ${url}
    uid: cortex_datasource
    isDefault: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: ${httpHeaderValue1}
    editable: false
