{
 "title": "Cgroup (container)",
 "tags": [
  "default",
  "cgroup"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_load_average_10s{instance=\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_start_time_seconds{instance=\"$instance\", name=\"${container:raw}\"} * 1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "timestamp(container_start_time_seconds{instance=\"$instance\", name=\"${container:raw}\"}) - container_start_time_seconds{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  {
   "title": "Load Avg(10s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{instance=\"$instance\", name=\"${container:raw}\"} / 1000"
    }
   ]
  },
  {
   "title": "Num of Task",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_tasks_state{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "description": "used: Cumulative cpu time consumed by container. Used ≠ user + system. For more information about this, refer to cgroups",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval]))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Usage (stack)",
   "type": "timeseries",
   "description": "system: Cumulative system cpu time consumed by container\n\nuser: Cumulative user cpu time consumed by container",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval]) / scalar(machine_cpu_cores{instance=\"$instance\"})",
     "legendFormat": "user"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=\"$instance\", name=\"${container:raw}\"}[$__rate_interval]) / scalar(machine_cpu_cores{instance=\"$instance\"})",
     "legendFormat": "system"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Swap Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_spec_memory_swap_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"} - container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "Swap Limit"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", name=\"${container:raw}\"} / (container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"} > 0)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(container_memory_swap{instance=\"$instance\", name=\"${container:raw}\"} / ((container_spec_memory_swap_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"} > 0) - container_spec_memory_limit_bytes{instance=\"$instance\", name=\"${container:raw}\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 } },
  {
   "title": "Usage",
   "type": "timeseries",
   "description": "rss: mapped anon pages. The amount of memory that doesn't correspond to anything on disk. anonymous + swap cache(includes transparent hugepages). This should not be confused with the RSS(Resident Set Size, rss + mapped_file)\n\nusage: total current memory usage by processes in the cgroup. It's a fuzz value for efficient access. If you want to know more exact memory usage, you should use rss + cache\n\nworking set: The amount of working set memory and it includes recently accessed memory, dirty memory. usage - inactive_file",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "container_memory_working_set_bytes{instance=\"$instance\",name=\"${container:raw}\"}",
     "legendFormat": "working set"
    },
    {
     "expr": "container_memory_rss{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "Rss"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_cache{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_swap{instance=\"$instance\", name=\"${container:raw}\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  }
 ]
}