{
 "title": "Overview",
 "tags": [
  "default",
  "host"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(up, hostname)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_uname_info{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{hostname=\"$hostname\"} * 1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "timestamp(node_boot_time_seconds{hostname=\"$hostname\"}) - node_boot_time_seconds{hostname=\"$hostname\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", hostname=\"$hostname\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{hostname=\"$hostname\", name!=\"/\"})"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 3, "w": 12, "x": 9, "y": 4 } },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{hostname=\"$hostname\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{hostname=\"$hostname\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{hostname=\"$hostname\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{hostname=\"$hostname\", mode=\"idle\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{hostname=\"$hostname\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{hostname=\"$hostname\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Mem Available",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"$hostname\"} / node_memory_MemTotal_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{hostname=\"$hostname\"} - node_memory_MemFree_bytes{hostname=\"$hostname\"}) / node_memory_MemTotal_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_SwapFree_bytes{hostname=\"$hostname\"} / node_memory_SwapTotal_bytes{hostname=\"$hostname\"})",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Usage by mode (stack)",
   "type": "timeseries",
   "description": "user: Time spent in user mode\n\nnide: Time spent in user mode with low priority (cide)\n\nsystem: Time spent in system mode\n\nidle: Time spend in the idle task\n\niowait: Time waiting for I/O to complete. This value is not reliable\n\nirq: Time servicing interrupts\n\nsoftirq: Time servicing softirqs\n\nsteal: Stolen time, which is the time spent in other operating systmes when running in a virtualized environment\n\nguest: Time spent running a virtual CPU for guest operating systems under the control of the Linux kernel\n\nguest_nice: Time spent running a niced guest (virtual CPU for guest operating systems under the control of the Linux kernel)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{hostname=\"$hostname\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{hostname=\"$hostname\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{hostname=\"$hostname\"}[$__rate_interval])))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (rate(node_cpu_guest_seconds_total{hostname=\"$hostname\"}[$__rate_interval])) /\nscalar(sum(rate(node_cpu_seconds_total{hostname=\"$hostname\"}[$__rate_interval])) + sum(rate(node_cpu_guest_seconds_total{hostname=\"$hostname\"}[$__rate_interval])))",
     "legendFormat": "{{mode}}(guest)"
    }
   ]
  },
  {
   "title": "Usage by Cgroup (stack)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(name)(rate(container_cpu_usage_seconds_total{name!=\"/\", hostname=\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage by JVM (stack)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{hostname=\"$hostname\", application=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true
  },
  {
   "title": "Free and Available",
   "type": "timeseries",
   "description": "free: Unused(empty) memory\n\navailable: Estimation of how much memory is available for starting new applications, without swapping",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"$hostname\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_MemFree_bytes{hostname=\"$hostname\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Used and Anonymous",
   "type": "timeseries",
   "description": "used: Used memory. fotal - free\n\ntotal: Total usable RAM (i.e., physical RAM minus a few reserved bits and the kernel binary code)\n\nanonymous: Active_anon + Inactive_anon. The amount of anonymous and tmpfs/shmem memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"} - node_memory_MemFree_bytes{hostname=\"$hostname\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Active_anon_bytes{hostname=\"$hostname\"} + node_memory_Inactive_anon_bytes{hostname=\"$hostname\"}",
     "legendFormat": "anonymous"
    }
   ]
  },
  {
   "title": "Buffers and Cached (stack)",
   "type": "timeseries",
   "description": "buffers: Buffer cache. Relatively temporary storage for raw disk blocks that shouldn't get tremendously large (20 MB or so)\n\ncached: In-memory cache for files read from the disk (the page cache).  Doesn't include SwapCached",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{hostname=\"$hostname\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{hostname=\"$hostname\"}",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Rss Usage by Cgroup (stack)",
   "type": "timeseries",
   "description": "rss: mapped anon pages. The amount of memory that doesn't correspond to anything on disk. anonymous + swap cache(includes transparent hugepages). This should not be confused with the RSS(Resident Set Size, rss + mapped_file)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{hostname=\"$hostname\", name!=\"/\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Usage by JVM (stack)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{hostname=\"$hostname\", application=~\".+\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  }
 ]
}