{
 "title": "JVM(non-Spring)",
 "tags": [
  "default",
  "jvm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } },
   {
    "name": "application",
    "query": {
     "query": "label_values(jvm_info{instance=\"$instance\"}, application)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(tomcat_requestcount_total{instance=\"$instance\", application=\"$application\"}, exported_port)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(tomcat_requestcount_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}, protocol)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Start time of the JVM",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\", application=\"$application\"} * 1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the JVM",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "timestamp(process_start_time_seconds{instance=\"$instance\", application=\"$application\"}) - process_start_time_seconds{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "File Descriptor Limit",
   "type": "stat",
   "description": "Usable maximum file descriptor count",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "JVM Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 } },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 17, "x": 0, "y": 4 } },
  {
   "title": "ClassLoader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "File Descriptor Used",
   "type": "stat",
   "description": "Opend file descriptor count",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Process RSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "description": "The \"recent cpu usage\" for the JVM process",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=\"$instance\", application=\"$application\"}"
    }
   ]
  },
  {
   "title": "BufferPool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", application=\"$application\"})",
     "legendFormat": "JVM"
    },
    {
     "expr": "sum(jvm_buffer_pool_used_bytes{instance=\"$instance\", application=\"$application\"})",
     "legendFormat": "non-JVM"
    }
   ]
  },
  {
   "title": "GC duration avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Tomcat connector ($port / $protocol)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "port",
   "collapsed": true,
   "panels": [
    {
     "title": "Req rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "expr": "rate(tomcat_requestcount_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval])",
       "legendFormat": "request"
      },
      {
       "expr": "rate(tomcat_errorcount_total {instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval])",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Req duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(tomcat_processingtime_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval]) / rate(tomcat_requestcount_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval])",
       "legendFormat": "req duration"
      },
      {
       "expr": "tomcat_maxtime_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "req duration (max)"
      }
     ]
    },
    {
     "title": "Req size mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(tomcat_bytessent_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval]) / rate(tomcat_requestcount_total{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}[$__rate_interval])",
       "legendFormat": "req size"
      }
     ]
    },
    {
     "title": "Thread state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_threadpool_pollerthreadcount{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "poller"
      },
      {
       "expr": "tomcat_threadpool_currentthreadcount{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "total"
      },
      {
       "expr": "tomcat_threadpool_currentthreadsbusy{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "busy"
      }
     ]
    },
    {
     "title": "Connection state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_threadpool_connectioncount{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "connection"
      },
      {
       "expr": "tomcat_threadpool_currentthreadsbusy{instance=\"$instance\", application=\"$application\", exported_port=\"$port\"}",
       "legendFormat": "busy"
      }
     ]
    }
   ]
  },
  { "title": "JVM GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "java_lang_garbagecollector_lastgcinfo_duration{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC duration avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool!~\"(Metaspace|Code Cache|Compressed Class Space)\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=~\"(Metaspace|Code Cache|Compressed Class Space)\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM MemoryPool Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_committed{instance=\"$instance\", area=\"heap\", application=\"$application\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_bytes_init{instance=\"$instance\", area=\"heap\", application=\"$application\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\", application=\"$application\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\", application=\"$application\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "non-Heap Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_committed{instance=\"$instance\", area=\"nonheap\", application=\"$application\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_bytes_init{instance=\"$instance\", area=\"nonheap\", application=\"$application\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\", application=\"$application\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\", application=\"$application\"}",
       "legendFormat": "max"
      }
     ]
    },
    { "type": "mxswat-separator-panel", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 } },
    {
     "title": "G1 Eden Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=\"G1 Eden Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\", application=\"$application\", pool=\"G1 Eden Space\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=\"G1 Eden Space\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\", application=\"$application\", pool=\"G1 Eden Space\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "G1 Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=\"G1 Survivor Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\", application=\"$application\", pool=\"G1 Survivor Space\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=\"G1 Survivor Space\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\", application=\"$application\", pool=\"G1 Survivor Space\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "G1 Old Gen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=\"G1 Old Gen\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\", application=\"$application\", pool=\"G1 Old Gen\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=\"G1 Old Gen\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\", application=\"$application\", pool=\"G1 Old Gen\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Metaspace or PermGen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=~\"(Metaspace|G1 Perm Gen)\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\", application=\"$application\", pool=~\"(Metaspace|G1 Perm Gen)\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=~\"(Metaspace|G1 Perm Gen)\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\", application=\"$application\", pool=~\"(Metaspace|G1 Perm Gen)\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Code Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=\"Code Cache\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pool_bytes_init{instance=\"$instance\", application=\"$application\", pool=\"Code Cache\"}",
       "legendFormat": "init"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\", application=\"$application\", pool=\"Code Cache\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_pool_bytes_max{instance=\"$instance\", application=\"$application\", pool=\"Code Cache\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_committed{instance=\"$instance\", application=\"$application\", pool=\"Compressed Class Space\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "java_lang_memorypool_usage_init{instance=\"$instance\", application=\"$application\", pool=\"Compressed Class Space\"}",
       "legendFormat": "init"
      },
      {
       "expr": "java_lang_memorypool_usage_used{instance=\"$instance\", application=\"$application\", pool=\"Compressed Class Space\"}",
       "legendFormat": "used"
      },
      {
       "expr": "java_lang_memorypool_usage_max{instance=\"$instance\", application=\"$application\", pool=\"Compressed Class Space\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "BufferPool (non-JVM Memory)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "BufferPool count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "JVM CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", application=\"$application\"}[$__rate_interval])",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 } },
  {
   "title": "Number of Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\", application=\"$application\"} - jvm_threads_daemon{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "non-daemon"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Number of Threads by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Deadlocked Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked_monitor{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "object monitors"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "ownable synchronizers"
    }
   ]
  }
 ]
}